version: "3"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app  
  nginx:
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    restart: always
    build:
      context: ./
    ports:
      - "80:80"
    