FROM node:14.14.0-alpine  as builder
WORKDIR /app/ui
COPY ./ui/package.json .
RUN npm install
COPY ./ui/ .
RUN npm run build

WORKDIR /app/server
COPY ./server/package.json .
RUN npm install
COPY ./server/ .
CMD ["npm", "run", "start"]

FROM nginx
EXPOSE 3000
COPY ./nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/ui/build /usr/share/nginx/html