FROM node:14.14.0-alpine  as builder
WORKDIR /app/ui
COPY ./ui/package.json .
RUN npm install
COPY ./ui/ .
RUN npm run start

WORKDIR /app/server
COPY ./server/package.json .
RUN npm install
COPY ./server/ .
CMD ["npm", "run", "start"]

FROM nginx
COPY ./nginx/dev.conf /etc/nginx/conf.d/default.conf
