version: "3"
services:
  nginx:
    depends_on:
      - backend
      - ui
    restart: always
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./ui/build:/usr/share/nginx/html
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  ui:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./ui/
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./ui:/app
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
